name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Fetch languages from private repo
      run: |
        curl -H "Authorization: token ${{ secrets.YOUR_NEW_GITHUB_TOKEN }}" \
             https://api.github.com/repos/shjeon-96/your-private-repo/languages \
             > languages.json

    - name: Install jq
      run: sudo apt-get install jq

    - name: Update README with new stats
      run: |
        # 모든 언어 통계 가져오기
        languages=$(jq -r 'to_entries | map("\(.key): \(.value) lines") | .[]' languages.json)

        # 언어 통계를 README.md에 삽입
        echo "$languages" | while IFS= read -r line; do
          sed -i "/<!-- LANGUAGES -->/a $line" README.md
        done

    - name: Commit changes
      run: |
        git add README.md
        git add languages.json  # languages.json 파일도 추가
        git commit -m "Update README with latest language stats"
        git push
