name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 18 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_NEW_GITHUB_TOKEN }} 
          USERNAME: shjeon-96
      - name: Commit & Push
        run: |
          git config user.name shjeon_96
          git config user.email tmdgns893758@gmail.com
          git add -A .
          git commit -m "generated"
          git push
