name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Fetch languages from private repo
      run: |
        repos=("reviewon-front-react" "reviewon-server-nestjs" "bupay-front-react" "sosomarket-webview" "baum-distri-homepage" "sosomarket-front-react" "sosomarket-app" "sosomarket-api")
        for repo in "${repos[@]}"; do
          curl -H "Authorization: token ${{ secrets.YOUR_NEW_GITHUB_TOKEN }}" \
               "https://api.github.com/repos/bubaum/$repo/languages" \
               > "$repo-languages.json"
        done

    - name: Install jq
      run: sudo apt-get install jq

    - name: Update README with new stats
      run: |
        # 모든 언어 통계 가져오기
        languages=""
        repos=("reviewon-front-react" "reviewon-server-nestjs" "bupay-front-react" "sosomarket-webview" "baum-distri-homepage" "sosomarket-front-react" "sosomarket-app" "sosomarket-api")
        for repo in "${repos[@]}"; do
          repo_languages=$(jq -r 'to_entries | map("\(.key): \(.value) lines") | .[]' "$repo-languages.json")
          languages+="$repo_languages"$'\n'
        done
        
        # 디버깅을 위한 출력 확인
        echo "$languages"  # 언어 통계를 출력해봅니다.
        
        # 언어 통계를 README.md에 삽입
        echo "$languages" | while IFS= read -r line; do
          printf "%s\n" "$line" >> README.md
        done
        
        # 변경 사항 확인
        cat README.md  # README.md의 변경 내용을 출력하여 확인합니다.

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Update README with latest language stats"
        git push
